apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab  # Создайте namespace заранее: kubectl create ns gitlab
spec:
  interval: 5m
  chart:
    spec:
      chart: gitlab
      version: "7.x.x"  # Укажите актуальную версию (проверьте здесь: https://charts.gitlab.io)
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  values:
    global:
      hosts:
        domain: example.com  # Ваш домен
      ingress:
        configureCertmanager: true
    certmanager:
      install: false  # Если у вас уже установлен cert-manager
    gitlab:
      webservice:
        replicas: 2
    postgresql:
      install: true
    redis:
      install: true