apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab
  namespace: flux-system
spec:
  interval: 15m
  path: ./apps/gitlab
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system  # Имя вашего основного GitRepository