apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          # Добавляем ресурсы
          resources:
            requests:
              cpu: 100m    # Минимум 0.1 ядра CPU
              memory: 128Mi  # Минимум 128 мебибайт RAM
            limits:
              cpu: 200m    # Максимум 0.2 ядра CPU
              memory: 256Mi  # Максимум 256 мебибайт RAM